name: clean artifacts

on:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: glassechidna/artifact-cleaner@master
        with:
          minimumAge: 43200 # all artifacts at least one day old
